In [ ]:
# python list
# list comprehension
# array module (import lib array)
# numpy array : 
#       zeros
#       ones
#       full
#       eye
#       arange
#       reshape
#       indexing

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [4]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [5]:
arr = np.arange(0,100)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [8]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [9]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [10]:
np.arange(-78,78)

array([-78, -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66,
       -65, -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53,
       -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40,
       -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27,
       -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14,
       -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,
         0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77])

In [11]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
# Difference between List and Numpy Array.
#In list, we can store different datatype elements. And in Numpy Array we can only store any 1 datatype elements
#Lists take time computing as it has multiple datatypes to deal with. Array computes faster as it only has to compute single datatype.

In [16]:
l2=np.array([0,1,2,3,4,5,6,7,8,9])

In [17]:
l2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
l3 = [str(x) for x in l2]

In [19]:
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [20]:
l4 = [x**2 for x in l2]

In [21]:
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [22]:
type(l4)

list

In [23]:
import array

In [24]:
help(array)

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array

    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined:
     |

In [25]:
arr = array.array('i', l2)

In [26]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
type(arr)

array.array

In [28]:
arr1 = array.array('i',[x**2 for x in l2])

In [29]:
arr1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [30]:
np.array(l2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.array([x + 3 for x in range(0,10)])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
np.array([x - 3 for x in range(0,10)])

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [33]:
np.array([1,2,3,4,5],dtype='float')

array([1., 2., 3., 4., 5.])

In [34]:
np.array([1,2,3,4,5],dtype=str)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [35]:
np.array([1,2,3,4,5],dtype=np.float64)

array([1., 2., 3., 4., 5.])

In [36]:
l2d = [[1,2,3],[4,5,6]]

In [38]:
l2d

[[1, 2, 3], [4, 5, 6]]

In [39]:
lc2d = [range(i,i+3) for i in [1,4,7]]

In [40]:
lc2d

[range(1, 4), range(4, 7), range(7, 10)]

In [41]:
np.array(lc2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [44]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [46]:
np.ones([2,2],dtype=int)

array([[1, 1],
       [1, 1]])

In [47]:
arr = np.ones([10,10], dtype = int)

In [48]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [49]:
arr[4:6,4:6] = 1

In [50]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [51]:
3.1*arr

array([[3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1]])

In [52]:
np.full((3,4),3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [53]:
arr = np.eye(3,dtype = int)

In [54]:
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [55]:
np.transpose(arr)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [56]:
arr1 = np.ones([6,6], dtype = int)

In [57]:
arr1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [58]:
np.full([6,6], 64, dtype = int)

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [59]:
#linspace functions where linspace means Linearly spaced elements.

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [60]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [61]:
#shallow copy
a=np.arange(1,10).reshape(3,3)

In [62]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [64]:
#deep copy
da=a[:2,:2].copy()

In [65]:
da

array([[1, 2],
       [4, 5]])

In [66]:
a[0,0]=11

In [67]:
a

array([[11,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [68]:
da

array([[1, 2],
       [4, 5]])

In [69]:
da[1,1]=5

In [70]:
da

array([[1, 2],
       [4, 5]])

In [71]:
a

array([[11,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [72]:
c=np.array([1,2,3,4])

In [73]:
c

array([1, 2, 3, 4])

In [74]:
c.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [75]:
arr1=np.arange(1,10).reshape(3,3)

In [76]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [4]:
arr=np.arange(0,9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
arr.reshape(1,9)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [7]:
arr.ravel?

Docstring:
a.ravel([order])

Return a flattened array.

Refer to `numpy.ravel` for full documentation.

See Also
--------
numpy.ravel : equivalent function

ndarray.flat : a flat iterator on the array.
Type:      builtin_function_or_method

In [8]:
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
arr.flatten?

Docstring:
a.flatten(order='C')

Return a copy of the array collapsed into one dimension.

Parameters
----------
order : {'C', 'F', 'A', 'K'}, optional
    'C' means to flatten in row-major (C-style) order.
    'F' means to flatten in column-major (Fortran-
    style) order. 'A' means to flatten in column-major
    order if `a` is Fortran *contiguous* in memory,
    row-major order otherwise. 'K' means to flatten
    `a` in the order the elements occur in memory.
    The default is 'C'.

Returns
-------
y : ndarray
    A copy of the input array, flattened to one dimension.

See Also
--------
ravel : Return a flattened array.
flat : A 1-D flat iterator over the array.

Examples
--------
>>> a = np.array([[1,2], [3,4]])
>>> a.flatten()
array([1, 2, 3, 4])
>>> a.flatten('F')
array([1, 3, 2, 4])
Type:      builtin_function_or_method

In [11]:
arr[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [12]:
#concatenation,joining of tw0 array
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 

In [13]:
np.concatenate([sa,da])

NameError: name 'sa' is not defined

In [14]:
a1=np.array([[1,1,1,1]])

In [15]:
a1

array([[1, 1, 1, 1]])

In [16]:
#row concatenate then number of coloumns must be equal
#col cincatenate then number of rows must be equal


In [17]:
import numpy as np

In [18]:
np.vstack?

Signature:       np.vstack(tup, *, dtype=None, casting='same_kind')
Call signature:  np.vstack(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vstack at 0x0000027ED7F0ED40>
File:            c:\users\avit\anaconda3\lib\site-packages\numpy\core\shape_base.py
Docstring:      
Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

``np.row_stack`` is an alias for `vstack`. They are the same function.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the first axis.
 

In [19]:
#stack arrays row wise 
arr=np.arange(9,18).reshape(3,3)
arr

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [20]:
ab=np.arange(1,4) 

In [21]:
ab

array([1, 2, 3])

In [22]:
np.vstack((arr,ab))

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [ 1,  2,  3]])

In [23]:
arr2=np.arange(1,4)
arr2=arr2[:,np.newaxis]

In [24]:
np.hstack((arr,arr2))

array([[ 9, 10, 11,  1],
       [12, 13, 14,  2],
       [15, 16, 17,  3]])

In [25]:
arr2

array([[1],
       [2],
       [3]])

In [26]:
np.split?

Signature:       np.split(ary, indices_or_sections, axis=0)
Call signature:  np.split(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function split at 0x0000027ED80499E0>
File:            c:\users\avit\anaconda3\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Split an array into multiple sub-arrays as views into `ary`.

Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

      - ary[:2]
      - ary[2:3]
      - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an empty sub-array is returned correspond

In [27]:
np.hsplit?

Signature:       np.hsplit(ary, indices_or_sections)
Call signature:  np.hsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function hsplit at 0x0000027ED8049B20>
File:            c:\users\avit\anaconda3\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Split an array into multiple sub-arrays horizontally (column-wise).

Please refer to the `split` documentation.  `hsplit` is equivalent
to `split` with ``axis=1``, the array is always split along the second
axis except for 1-D arrays, where it is split at ``axis=0``.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.hsplit(x, 2)
[array([[  0.,   1.],
       [  4.,   5.],
       [  8.,   9.],
       [12.,  13.]]),
 array([[  2.,   3.],
       [  6.,   7.],
       [10., 

In [28]:
np.vsplit?

Signature:       np.vsplit(ary, indices_or_sections)
Call signature:  np.vsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vsplit at 0x0000027ED8049BC0>
File:            c:\users\avit\anaconda3\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
>>> np.vsplit(x, np.array([3, 6]))
[array(

In [29]:
np.dsplit?

Signature:       np.dsplit(ary, indices_or_sections)
Call signature:  np.dsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function dsplit at 0x0000027ED8049C60>
File:            c:\users\avit\anaconda3\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Split array into multiple sub-arrays along the 3rd axis (depth).

Please refer to the `split` documentation.  `dsplit` is equivalent
to `split` with ``axis=2``, the array is always split along the third
axis provided the array dimension is greater than or equal to 3.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(2, 2, 4)
>>> x
array([[[ 0.,   1.,   2.,   3.],
        [ 4.,   5.,   6.,   7.]],
       [[ 8.,   9.,  10.,  11.],
        [12.,  13.,  14.,  15.]]])
>>> np.dsplit(x, 2)
[array([[[ 0.,  1.],
        [ 4.,  5.]],
       [[ 8.,  9.],
        [12., 13.]]]), array([[[ 2.,  3.],
        [ 6.,  7.]],
       

In [30]:
a1=np.array([1,2,3,4,5,6])

In [31]:
a1

array([1, 2, 3, 4, 5, 6])

In [32]:
np.split(a1,[2,4]) #number split in a range 

[array([1, 2]), array([3, 4]), array([5, 6])]

In [33]:
np.vsplit(arr,[1,2])

[array([[ 9, 10, 11]]), array([[12, 13, 14]]), array([[15, 16, 17]])]

In [34]:
np.hsplit(arr,[1,2])

[array([[ 9],
        [12],
        [15]]),
 array([[10],
        [13],
        [16]]),
 array([[11],
        [14],
        [17]])]

In [35]:
r=np.arange(1,28).reshape(3,3,3)

In [36]:
r

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [37]:
np.dsplit(r,3)

[array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]]),
 array([[[ 3],
         [ 6],
         [ 9]],
 
        [[12],
         [15],
         [18]],
 
        [[21],
         [24],
         [27]]])]

In [38]:
t=np.arange(1,10).reshape(3,3)

In [39]:
t

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.sum(t)

45

In [41]:
np.sum(t,axis=0)

array([12, 15, 18])

In [42]:
np.sum(t,axis=1)

array([ 6, 15, 24])

In [43]:
np.min(t)

1

In [44]:
np.max(t)

9

In [45]:
# Index of min
np.argmin(t)

0

In [46]:
# Index of max
np.argmax(t)

8

In [47]:
np.abs(t)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.var(t)

6.666666666666667

In [49]:
np.median(t)

5.0

In [50]:
np.prod(t)

362880

In [51]:
np.empty?

Docstring:
empty(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of uninitialized (arbitrary) data of the gi

In [52]:
a1=np.random.randint(0,18,(6,6))

In [53]:
a1

array([[10,  6,  5, 11,  8, 17],
       [ 1,  5,  2, 10,  4, 16],
       [ 0, 11, 10,  0, 11, 11],
       [ 3, 10, 10,  2,  8, 15],
       [ 9,  6,  2, 14, 12,  7],
       [ 0,  9,  4, 14,  4, 13]])

#slicing and indexing

In [55]:
a1[2:5:2]

array([[ 0, 11, 10,  0, 11, 11],
       [ 9,  6,  2, 14, 12,  7]])

In [56]:
a1[::-1]

array([[ 0,  9,  4, 14,  4, 13],
       [ 9,  6,  2, 14, 12,  7],
       [ 3, 10, 10,  2,  8, 15],
       [ 0, 11, 10,  0, 11, 11],
       [ 1,  5,  2, 10,  4, 16],
       [10,  6,  5, 11,  8, 17]])

In [57]:
a1[0:3,1:3]

array([[ 6,  5],
       [ 5,  2],
       [11, 10]])

In [58]:
a1[0:3,0:3]

array([[10,  6,  5],
       [ 1,  5,  2],
       [ 0, 11, 10]])

In [59]:
a1[2:5,3:5]

array([[ 0, 11],
       [ 2,  8],
       [14, 12]])

In [60]:
a1[::,::]

array([[10,  6,  5, 11,  8, 17],
       [ 1,  5,  2, 10,  4, 16],
       [ 0, 11, 10,  0, 11, 11],
       [ 3, 10, 10,  2,  8, 15],
       [ 9,  6,  2, 14, 12,  7],
       [ 0,  9,  4, 14,  4, 13]])

In [61]:
a1[::2,::]

array([[10,  6,  5, 11,  8, 17],
       [ 0, 11, 10,  0, 11, 11],
       [ 9,  6,  2, 14, 12,  7]])

In [62]:
a1[::,::2]

array([[10,  5,  8],
       [ 1,  2,  4],
       [ 0, 10, 11],
       [ 3, 10,  8],
       [ 9,  2, 12],
       [ 0,  4,  4]])

In [63]:
a1[::-1,::]

array([[ 0,  9,  4, 14,  4, 13],
       [ 9,  6,  2, 14, 12,  7],
       [ 3, 10, 10,  2,  8, 15],
       [ 0, 11, 10,  0, 11, 11],
       [ 1,  5,  2, 10,  4, 16],
       [10,  6,  5, 11,  8, 17]])

In [64]:
a1[::-1,::-1]

array([[13,  4, 14,  4,  9,  0],
       [ 7, 12, 14,  2,  6,  9],
       [15,  8,  2, 10, 10,  3],
       [11, 11,  0, 10, 11,  0],
       [16,  4, 10,  2,  5,  1],
       [17,  8, 11,  5,  6, 10]])

#Assignment 1
1. Import Numpy as np
2. Create an array of 10 zeros
3. Create an array of 10 ones
4. Create an array of the integers from 10 to 50
5. Create an array of all the even integers from 10 to 50
6. Create a 3x3 matrix with values ranging from 0 to 8
7. Create a 3x3 identity matrix
8. use NumPy to generate a random number between 0 to 1
9. Use Numpy to generate an array of 25 random numbers sampled from
a standard normal distribution
10. Create a matrix of 10x10 matrix of linearly spaced elements from
0.01 to 1
11. Create an array of 20 linearly spaced points between 0 and 1
12. Create a 5x5 matrix as
array([[ 1, 2, 3, 4, 5],
       [ 6, 7, 8, 9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
find following using slicing
a. array([[12, 13, 14, 15],
          [17, 18, 19, 20],
          [22, 23, 24, 25]])
b. 20
c. array([[ 2],
         [ 7],
         [12]])
d.array([21, 22, 23, 24, 25])
e.array([[16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]])
13. Get sum of all values in matrix
14. Get sum of all the columns in matrix
15. Get Standard deviation , varience , minimum, maximum from matrix
row wis.
16. create 2 d matrix with all border values nan

In [65]:
#1
import numpy as np 


In [66]:
#q2
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
#q3
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [68]:
#q4
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [69]:
#q5
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [70]:
#q6
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
#q7
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
#q8
np.random.random(1)

array([0.1275003])

In [73]:
#q9
np.random.randn(25)

array([-1.03065312,  1.36571113, -1.45559231, -0.88760562,  0.63497321,
       -0.84239509,  1.34460729,  0.20414182, -0.70001502, -0.11647864,
       -0.091846  ,  1.09081606,  1.24700189, -0.96612383,  1.32807062,
        0.57889562, -1.68466118,  1.80385393, -1.31459747,  0.17568267,
        0.4858906 , -0.95113112, -0.41826107, -0.7482765 ,  0.4410083 ])

In [74]:
#q10
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [75]:
#q11
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [76]:
#q12
a=np.arange(1,26).reshape(5,5)

In [77]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [78]:
#q12(a)
a[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [79]:
#q12(b)
a[3,4]

20

In [80]:
#q12(c)
a[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [81]:
#q12(d)
a[4]

array([21, 22, 23, 24, 25])

In [82]:
#q12(e)
a[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [83]:
#q13
np.sum(a)

325

In [84]:
#q14
np.sum(a,axis=0)

array([55, 60, 65, 70, 75])

In [85]:
#q15
std= np.std(a, axis=1)

In [86]:
std

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [87]:
var= np.var(a, axis=1)

In [88]:
var

array([2., 2., 2., 2., 2.])

In [89]:
min= np.min(a, axis=1)

In [90]:
min

array([ 1,  6, 11, 16, 21])

In [91]:
max= np.max(a, axis=1)

In [92]:
max

array([ 5, 10, 15, 20, 25])

In [93]:
#q16
rows, cols = 5, 5
B= np.zeros((rows, cols))
B[0, :] = np.nan  
B[-1, :] = np.nan
B[:, 0] = np.nan
B[:, -1] = np.nan

In [94]:
B

array([[nan, nan, nan, nan, nan],
       [nan,  0.,  0.,  0., nan],
       [nan,  0.,  0.,  0., nan],
       [nan,  0.,  0.,  0., nan],
       [nan, nan, nan, nan, nan]])

#Assignment 2
1. Create 1-D, 2-D and 3-D numpy array
2. Print data type of array.
3. Print shape and dimensions of all the three different array.
4. Create another 1-D array of 12 elements filled with zero
5. Create another 2-D array elements filled with ones.
6. Create a 1-D array known as Maths Marks out of 100 having 20
elements.
7. Sort the above array in ascending and descending order.
8. Create a copy of sorted array to another variable by deep copying.
9. Create 2-D array of 5x5 which is an identity matrix and then convert
1D .
10. Create 2-D array of 3x3. Add one more row to it.
11. Split above array created vertically and horizontally.
12. Create 4x4 identity matrix. Add 4 to each element.
13. Create 1-D array. Initialize with floating point values. Display its ceil,
floor and round (with 2 decimal’s).
14. Create 5x5 matrix. Display min, max, variance and standard
deviation column-wise.
15. Create a null vector of size 10 with 6th value filled with 200.
16. Create a 1-D Array/Vector with values ranging from 100 to 150 in
sequence.
17. Reverse the above vector.
18. Create a 5x5 matrix with values ranging from 0-24 using some
function.
19. Find indices of nonzero elements from [1,0,2,0,0,4,0,8]
20. Create a 10x10 matrix with 1 on the borders and 0 inside.
21. Create 8x8 matrix and fill with 1 and 0 in checkerboard pattern.
22. Create two 3x3 matrix with random integer values. Perform matrix
addition, multiplication and subtraction

In [95]:
import numpy as np

In [96]:
#q1
a1=np.arange(5)

In [97]:
a1

array([0, 1, 2, 3, 4])

In [98]:
a2=np.arange(4).reshape(2,2)

In [99]:
a2

array([[0, 1],
       [2, 3]])

In [100]:
a3=np.arange(8).reshape(2,2,2)

In [101]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [102]:
#q2
a3.dtype

dtype('int32')

In [103]:
#q3
np.ndim(a1)

1

In [104]:
np.shape(a1)

(5,)

In [105]:
np.shape(a2)

(2, 2)

In [106]:
np.ndim(a2)

2

In [107]:
np.shape(a3)

(2, 2, 2)

In [108]:
np.ndim(a3)

3

In [109]:
#q4
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [110]:
#q5
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [111]:
#q6
s=np.random.randint(0, 101, 20)

In [112]:
s

array([78, 53, 96, 34,  9, 21, 18, 73, 30, 44, 54, 75, 70, 93, 27, 77, 88,
        1, 46, 76])

In [113]:
#q7
p=np.sort(s) #ascending order

In [114]:
p

array([ 1,  9, 18, 21, 27, 30, 34, 44, 46, 53, 54, 70, 73, 75, 76, 77, 78,
       88, 93, 96])

In [115]:
q=np.sort(s)[::-1] #descending order

In [116]:
q

array([96, 93, 88, 78, 77, 76, 75, 73, 70, 54, 53, 46, 44, 34, 30, 27, 21,
       18,  9,  1])

In [117]:
#q8
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [118]:
np.sort(a3)
t=a3.copy()
t[0]=24

In [119]:
t

array([[[24, 24],
        [24, 24]],

       [[ 4,  5],
        [ 6,  7]]])

In [120]:
#q9
k=np.eye(5)


In [121]:
k

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [122]:
u=k.flatten()

In [123]:
u

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [124]:
#q10
b=np.arange(1,10).reshape(3,3)

In [125]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
b1=np.arange(11,14).reshape(1,3)

In [127]:
b1

array([[11, 12, 13]])

In [128]:
b2=np.concatenate((b,b1), axis=0)

In [129]:
b2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [130]:
#q11
v1=np.vsplit(b2,2)

In [131]:
v1

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [11, 12, 13]])]

In [132]:
h1=np.hsplit(b2,3)

In [133]:
h1

[array([[ 1],
        [ 4],
        [ 7],
        [11]]),
 array([[ 2],
        [ 5],
        [ 8],
        [12]]),
 array([[ 3],
        [ 6],
        [ 9],
        [13]])]

In [134]:
#q12
e=np.eye(4)

In [135]:
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [136]:
e1=e+4

In [137]:
e1

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [138]:
 #q13
r=np.array([-2.45,4.65,6.78,-8.90])
r1=np.ceil(r)

In [139]:
r1

array([-2.,  5.,  7., -8.])

In [140]:
r2=np.floor(r)

In [141]:
r2

array([-3.,  4.,  6., -9.])

In [142]:
r3=np.round(r,2)

In [143]:
r3

array([-2.45,  4.65,  6.78, -8.9 ])

In [144]:
#q14
y=np.arange(1,26).reshape(5,5)

In [145]:
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [147]:
min=np.min(y,axis=0)

In [148]:
min

array([1, 2, 3, 4, 5])

In [149]:
max=np.max(y,axis=0)

In [150]:
max

array([21, 22, 23, 24, 25])

In [151]:
var=np.var(y,axis=0)

In [152]:
var

array([50., 50., 50., 50., 50.])

In [153]:
std=np.std(y,axis=0)

In [154]:
std

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [155]:
#q15
m=np.zeros(10)
m[5]=200

In [156]:
m

array([  0.,   0.,   0.,   0.,   0., 200.,   0.,   0.,   0.,   0.])

In [157]:
#q16
f=np.arange(100,151)

In [158]:
f

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [159]:
#q17
c=f[::-1]

In [160]:
c

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [161]:
#q18
w=np.array([1,0,2,0,0,4,0,8])
v=np.nonzero(w)[0]

In [162]:
w

array([1, 0, 2, 0, 0, 4, 0, 8])

In [163]:
v

array([0, 2, 5, 7], dtype=int64)

In [164]:
#q19
j=np.zeros((10,10),dtype=int)

In [165]:
j

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [166]:
j[0,:]=1

In [167]:
j

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [168]:
j[:,0]=1
j[:,-1]=1

In [169]:
j

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [170]:
#q20
h=np.zeros((8,8),dtype=int)
h[1::2,::2]=1
h[::2,1::2]=1


In [171]:
h

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [172]:
#q21
l= np.zeros((8, 8), dtype=int)
l[1::2, ::2] = 1
l[::2, 1::2] = 1



In [173]:
l

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [174]:
#q22
d1=np.random.randint(1,20, size=(3, 3))
d2=np.random.randint(11,30, size=(3, 3))
add1=d1+d2
mul1=np.dot(d1,d2)
sub1=d1-d2

In [175]:
add1

array([[23, 27, 41],
       [28, 24, 36],
       [40, 19, 24]])

In [176]:
np.dot?

Call signature:  np.dot(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function dot>
Docstring:      
dot(a, b, out=None)

Dot product of two arrays. Specifically,

- If both `a` and `b` are 1-D arrays, it is inner product of vectors
  (without complex conjugation).

- If both `a` and `b` are 2-D arrays, it is matrix multiplication,
  but using :func:`matmul` or ``a @ b`` is preferred.

- If either `a` or `b` is 0-D (scalar), it is equivalent to
  :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
  preferred.

- If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
  the last axis of `a` and `b`.

- If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
  sum product over the last axis of `a` and the second-to-last axis of
  `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

It uses an optimized BLAS library when possible (see `numpy.linalg`).

Parameters
----------
a : array_like
    Fi

In [177]:
mul1

array([[438, 315, 345],
       [633, 459, 513],
       [700, 675, 735]])

In [178]:
sub1

array([[-15, -21, -15],
       [-14, -18,   2],
       [ -6,  -5,  -4]])